[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "datasmryzr"
dynamic = ["version"]
description = ''
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
keywords = []
authors = [
  { name = "Kristy Horan", email = "kristyhoran15@gmail.com" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
              "click",
              "pandas",
              "jinja2",
              "altair",
              "mycolorpy",
              "numpy",
              ]

[project.urls]
Documentation = "https://github.com/kristyhoran/datasmryzr#readme"
Issues = "https://github.com/kristyhoran/datasmryzr/issues"
Source = "https://github.com/kristyhoran/datasmryzr"


[project.scripts]
datasmryzr = "datasmryzr.datasmryzr:main"



[tool.hatch.version]
path = "src/datasmryzr/__about__.py"

[tool.hatch.envs.types]
extra-dependencies = [
  "mypy>=1.0.0",
]
[tool.hatch.envs.types.scripts]
check = "mypy --install-types --non-interactive {args:src/datasmryzr tests}"

[tool.coverage.run]
source_pkgs = ["datasmryzr", "tests"]
branch = true
parallel = true
omit = [
  "src/datasmryzr/__about__.py",
]

[tool.coverage.paths]
datasmryzr = ["src/datasmryzr", "*/datasmryzr/src/datasmryzr"]
tests = ["tests", "*/datasmryzr/tests"]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]
